--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/WorldManager
build-by-default: true
branches:
- main
projects:
  WorldManager:
    path: ""
    libs:
      Commando:
        src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
      VanillaGenerator:
        src: CzechPMDevs/VanillaGenerator/VanillaGenerator
        version: ^0.0.6
    lint: false
...
